### ISSUE TITLE
Docker in docker issues

### ISSUE THREAD

**Issue by adben** [dasniko/quarkus-keycloak#2]
Is there any suggestion or pointers regarding using alternatives to testcontainers?

**Comment by dasniko** [comment]
You are free to use something different, e.g. the automatically started Keycloak container with the Quarkus dev services (which I disabled with https://github.com/dasniko/quarkus-keycloak/blob/3219203e8c8081b288777bc92f59f4d3ab0bcbba/src/main/resources/application.properties#L3).
